# Generated by Django 2.1.7 on 2019-02-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crumbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(verbose_name='date of expense'),
        ),
    ]
