# Generated by Django 2.1.7 on 2019-02-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crumbs', '0002_auto_20190215_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='date of expense'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='purpose',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
