# Generated by Django 2.1.7 on 2019-02-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crumbs', '0004_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt',
            field=models.ImageField(upload_to='receipts/'),
        ),
    ]
