# Generated by Django 2.1.7 on 2019-02-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crumbs', '0005_auto_20190225_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt',
            field=models.FileField(upload_to='receipts/'),
        ),
    ]
